cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
  path('add/<int:product_id>/', views.add_cart, name='add_cart'),
  path('', views.cart_detail, name='cart_detail'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
  path('delete/<int:product_id>/', views.full_remove, name='full_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns=[
  # maps all products
  path('',views.allProdCat, name='allProdCat'),
  # maps all products by category
  path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
  # map the product detail page
  path('<slug:c_slug>/<slug:product_slug>/',
    views.ProdCatDetail, name='ProdCatDetail'),
]

shoppingcart/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('shop/', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('accounts/create', views.signUpView, name='signup'),
    # path('accounts/signin', views.signInView, name='signin'),
    path('accounts/login', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# alternative taught in https://www.udemy.com/develop-a-shopping-cart-website-with-django-2-and-python-3
# if settings.DEBUG:
#  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
  cart_id = models.CharField(max_length=250, blank=True)
  date_added = models.DateField(auto_now=True)
  class Meta:
    db_table = 'Cart'
    ordering = ['date_added']

  def __str__(self):
    return self.cart_id

class CartItem(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
  quantity = models.IntegerField()
  active = models.BooleanField(default=True)

  class Meta:
    db_table = 'CartItem'

  def sub_total(self):
    return self.product.price * self.quantity

  def __str__(self):
    return self.product

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderItem
from django.template.loader import get_template
from django.core.mail import EmailMessage


def _cart_id(request):
    # check to see if a session id has been created
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    # if cart doesn't exist, create one with a session id
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request),
        )
        cart.save()
    # if cart_item exists add a value of 1 to the existing value
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    # if cart_item doesn't exist, create a cart_item and give it the valuie of 1
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product, quantity=1, cart=cart)
        cart_item.save()
        # return the detailed cart view
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total*100)
    description = 'Books Inc - New Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        print(request.POST)
        try:
            # pull data from the Stripe form on submission
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            # push this data to the order app
            billingName = request.POST['stripeBillingName']
            billingAddress1 = request.POST['stripeBillingAddressLine1']
            billingCity = request.POST['stripeBillingAddressCity']
            billingPostCode = request.POST['stripeBillingAddressZip']
            billingCountry = request.POST['stripeBillingAddressCountry']
            shippingName = request.POST['stripeShippingName']
            shippingAddress1 = request.POST['stripeShippingAddressLine1']
            shippingCity = request.POST['stripeShippingAddressCity']
            shippingPostCode = request.POST['stripeShippingAddressZip']
            shippingCountry = request.POST['stripeShippingAddressCountry']

            customer = stripe.Customer.create(
                email=email,
                source=token,
            )
            charge = stripe.Charge.create(
                amount=stripe_total,
                currency='gbp',
                description=description,
                customer=customer.id,
            )
            try:
                # creating the order
                order_details = Order.objects.create(
                    token=token,
                    total=total,
                    email=email,
                    billingName=billingName,
                    billingAddress1=billingAddress1,
                    billingCity=billingCity,
                    billingPostCode=billingPostCode,
                    billingCountry=billingCountry,
                    shippingName=shippingName,
                    shippingAddress1=shippingAddress1,
                    shippingCity=shippingCity,
                    shippingPostCode=shippingPostCode,
                    shippingCountry=shippingCountry,
                )
                order_details.save()
                # now to create the order item record
                for order_item in cart_items:
                    # every time the for loop runs, a cart item is assigned to the order item variable
                    oi = OrderItem.objects.create(
                        product=order_item.product.name,
                        quantity=order_item.quantity,
                        price=order_item.product.price,
                        order=order_details,
                    )
                    oi.save()
                    # reduce the stock once an order is placed
                    products = Product.objects.get(id=order_item.product.id)
                    products.stock = int(
                        order_item.product.stock - order_item.quantity)
                    products.save()
                    order_item.delete()
                    # Print message to terminal on order completion
                    print('The order has been completed')
                try:
                    # calling the send email funtion
                    sendEmail(order_details.id)
                    print('The order email has been sent to the customer')
                except ImportError as e:
                    return e
                return redirect('order:thanks', order_details.id)
            except ObjectDoesNotExist:
                pass
        except stripe.error.CardError as e:
            return False, e
    return render(request, 'cart/cart.html', dict(
        cart_items=cart_items,
        total=total,
        counter=counter,
        data_key=data_key,
        stripe_total=stripe_total,
        description=description))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')


def sendEmail(order_id):
    transaction = Order.objects.get(id=order_id)
    order_items = OrderItem.objects.filter(order=transaction)
    try:
        # sending the order to the customer
        subject = 'Books Inc - New Order #{}'.format(transaction.id)
        to = ['{}'.format(transaction.email)]
        from_email = 'order@booksinc.com'
        order_information = {
            'transaction': transaction,
            'order_items': order_items
        }
        message = get_template('email/email.html').render(order_information)
        msg = EmailMessage(subject, message, to=to, from_email=from_email)
        msg.content_subtype = 'html'
        print(to, from_email, subject, order_information)
        msg.send()
    except IOError as e:
        return e

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block metadescription %}
This is the shopping cart. Please review the items and place the order
{% endblock %}

{% block title %}
Shopping Cart - Books Inc Store
{% endblock %}

{% block content %}

{% if not cart_items %}

<h2 class="title">Your shopping cart is empty</h2>
<p class='subtitle'>Please click <a href="{% url 'shop:allProdCat' %}" class="has-text-link">here</a> to continue
  shopping</p>
{% else %}

<h1 class="title has-text-centered">Your Shopping Cart</h1>
<div class="columns">
  <!-- 1st Column -->
  <div class="column">
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th class='subtitle has-text-centered has-background-grey-lighter is-uppercase has-text-weight-semibold	'>
            Items</th>
        </tr>
      </thead>
      <tbody>
        {% for cart_item in cart_items %}
        <tr style="border: none;">
          <td style="border: none;">
            <div class="columns is-mobile">
              <div class="column is-one-quarter">
                <a href="{{ cart_item.product.get_url }}">
                  <figure class=" image is-64x64">
                    <img src="{{cart_item.product.image.url}}" alt="Placeholder image">
                  </figure>
                </a>
              </div>
              <div class="column is-one-half has-text-left">
                <p class="title is-5">{{cart_item.product.name}}</p>
                <p class="subtitle is-6" style="margin-bottom: 0.5rem;">{{cart_item.product.author}}</p>
                <!-- <p>{{cart_item.product.description|truncatewords:20}}</p> -->
                <p>Quantity: {{cart_item.quantity}}</p>
                <p>Unit price: £{{cart_item.product.price}}</p>
                <p>Sub Total: £{{cart_item.sub_total}}</p>
              </div>
              <div class="column is-one-quarter">
                {% if cart_item.quantity < cart_item.product.stock %}
                <p class="has-text-right is-size-5-mobile is-size-4-tablet">
                  <a href="{% url 'cart:add_cart' cart_item.product.id %}" class='has-text-success'>
                    <i class="fas fa-plus-square"></i>
                  </a>
                  <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class='has-text-warning'>
                    <i class="fas fa-minus-square"></i>
                  </a>
                  <a href="{% url 'cart:full_remove' cart_item.product.id %}" class='has-text-danger'>
                    <i class="fas fa-trash-alt"></i>
                  </a>
                </p>
                {% else %}
                <p class="has-text-right is-size-5-mobile is-size-4-tablet">
                  <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class='has-text-warning'>
                    <i class="fas fa-minus-square"></i>
                  </a>
                  <a href="{% url 'cart:full_remove' cart_item.product.id %}" class='has-text-danger'>
                    <i class="fas fa-trash-alt"></i>
                  </a>
                </p>
                {% endif %}
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- 2nd Column -->

  <div class="column">
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th class='subtitle has-text-centered has-background-grey-lighter is-uppercase has-text-weight-semibold	'>
            Checkout</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            Please review your shopping cart items before proceeding with the order payment
          </td>
        </tr>
        <tr>
          <td>
            Your Total is <strong>£{{ total }}</strong>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="has-text-centered">
      <form action="" method="POST">
        {% csrf_token %}
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="{{ data_key }}"
          data-amount="{{ stripe_total }}" data-name="Books Inc" data-description="{{ description }}"
          data-image="{% static 'shoppingcart-logo.png' %}" data-locale="auto" data-currency="gbp"
          data-shipping-address='True' data-billing-address='True' data-zip-code='True'>
          </script>
      </form>
      <br>
      <a class="button is-link" href="{% url 'shop:allProdCat' %}">Continue Shopping</a>
    </div>
  </div>
</div>

{% endif %}
{% endblock %}