cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
  path('add/<int:product_id>/', views.add_cart, name='add_cart'),
  path('', views.cart_detail, name='cart_detail'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
  path('delete/<int:product_id>/', views.full_remove, name='full_remove'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
  path('', views.searchResult, name='searchResult')
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns=[
  # maps all products
  path('',views.allProdCat, name='allProdCat'),
  # maps all products by category
  path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
  # map the product detail page
  path('<slug:c_slug>/<slug:product_slug>/',
    views.ProdCatDetail, name='ProdCatDetail'),
]

shoppingcart/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('shop/', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('accounts/create', views.signUpView, name='signup'),
    # path('accounts/signin', views.signInView, name='signin'),
    path('accounts/login', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# alternative taught in https://www.udemy.com/develop-a-shopping-cart-website-with-django-2-and-python-3
# if settings.DEBUG:
#  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingcart/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}

<head>
  <meta charset="utf-8">
  <meta name='description' content="{% block metadescription %}{% endblock %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shopping Cart</title>
  <link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <script src="{% static 'js/fontawesome.js' %}"></script>
</head>

<body>

  <!-- Navbar -->

  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class='container'>
      <div class="navbar-brand">
        <a class="navbar-item" href="\">
          <img src="{% static 'shoppingcart-logo.png' %}" width="28" height="28">
        </a>

        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>

      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Shop</a>
            <div class="navbar-dropdown">
              <a class="navbar-item" href='{% url "shop:allProdCat" %}'>
                All Products
              </a>
              {% for cat in links %}
              <a class="navbar-item " href='{{cat.get_url}}'>{{cat.name}}</a>
              {% endfor %}
            </div>
          </div>
          {% if item_count > 0 %}

          <a class="navbar-item has-text-grey-dark" href="{% url 'cart:cart_detail' %}">
            <i class="fas fa-shopping-cart"></i>
            <p>(<span class="has-text-danger">{{item_count}}</span>)</p>
          </a>

          {% endif %}
        </div>

        <div class="navbar-end">

          <!-- <div class="navbar-item">
            <form class="is-horizontal">
              <field class="is-horizontal">
                <field-body>
                  <input class="input" type="text" placeholder="Search">
                  <button class="button is-link">Search</button>
                </field-body>
              </field>
            </form>
          </div> -->

          <div class="navbar-item">
            <form action="{% url 'search:searchResult' %}" method="GET">
              {% csrf_token %}
              <div class="field is-horizontal">
                <div class="field-body">
                  <div class="field">
                    <input class="input is-one-quarter-mobile" type="text" placeholder="Search" name="q">
                  </div>
                  <div class="field">
                    <button class="button is-link" type="input"><i class="fas fa-search"></i></button>
                  </div>
                </div>
              </div>
            </form>
          </div>

          <div class="navbar-item">
            <div class="buttons">
              {% if request.user.is_authenticated %}
              <div>
                <a class="button has-icons-left has-background-grey-lighter" href="{% url 'order:order_history' %}">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                  <p>{{ request.user.username }} </p>
                </a>
                <p></p>
              </div>
              <a class="button is-danger" href='{% url "logout" %}'>
                Log Out
              </a>
              {% else %}
              <a class="button is-link" href='{% url "signup" %}'>
                Sign up
              </a>
              <a class="button is-success" href='{% url "login" %}'>
                Log in
              </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <!-- Content Above The Fold -->

  <section class="hero is-light is-fullheight-with-navbar">
    <div class="hero-body">
      <div class="container">
        {% block content %}
        {% endblock %}

      </div>
    </div>
  </section>

  <!-- Content Below the Fold -->


  <!-- Footer -->

  <footer class="footer">
    <div class="content has-text-centered">
      <p><a href=''>Privacy</a> | <a href=''>Terms</a> | <a href=''> Contact</a> | Copyright 2018 - {% now 'Y' %}</p>
    </div>
  </footer>

  <!-- Javascript -->

  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

</body>

</html>